package polka:repository@0.1.0;

interface blockstore {
  read-block: func(
    cid: list<u8>
  ) -> list<u8>;

  write-block: func(
    codec: u64,
    hash: u64,
    contents: list<u8>
  ) -> list<u8>;
}

interface crypto {
  sign: func(bytes: list<u8>) -> list<u8>;
}

interface repo {
  record get-result {
    rpath: string,
    data: string
  }

  resource repo {
    get-cid: func(rpath: string) -> result<string, string>;
    get-record: func(rpath: string) -> result<get-result, string>;
    get-records: func(nsid: string) -> result<list<get-result>, string>;
    all-records: func() -> result<list<get-result>, string>;
    get-root: func() -> result<string, string>;

    create: func(rpath: string, data: string) -> result<string, string>;
    update: func(rpath: string, data: string) -> result<string, string>;
    delete: func(rpath: string) -> result<bool, string>;
  }

  create: func(did: string) -> result<repo, string>;
  open: func(did: string, cid: string) -> result<repo, string>;
}

world repository {
  import blockstore;
  import crypto;
  export repo;
}
