// Code generated by ent, DO NOT EDIT.

package record

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the record type in the database.
	Label = "record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldSig holds the string denoting the sig field in the database.
	FieldSig = "sig"
	// FieldPk holds the string denoting the pk field in the database.
	FieldPk = "pk"
	// Table holds the table name of the record in the database.
	Table = "records"
)

// Columns holds all SQL columns for record fields.
var Columns = []string{
	FieldID,
	FieldContent,
	FieldSig,
	FieldPk,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// SigValidator is a validator for the "sig" field. It is called by the builders before save.
	SigValidator func(string) error
	// PkValidator is a validator for the "pk" field. It is called by the builders before save.
	PkValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Record queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// BySig orders the results by the sig field.
func BySig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSig, opts...).ToFunc()
}

// ByPk orders the results by the pk field.
func ByPk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPk, opts...).ToFunc()
}
