// Code generated by ent, DO NOT EDIT.

package record

import (
	"entgo.io/ent/dialect/sql"
	"github.com/marukun712/polka/pds/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldID, id))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldContent, v))
}

// Sig applies equality check predicate on the "sig" field. It's identical to SigEQ.
func Sig(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldSig, v))
}

// Pk applies equality check predicate on the "pk" field. It's identical to PkEQ.
func Pk(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldPk, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldContent, v))
}

// SigEQ applies the EQ predicate on the "sig" field.
func SigEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldSig, v))
}

// SigNEQ applies the NEQ predicate on the "sig" field.
func SigNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldSig, v))
}

// SigIn applies the In predicate on the "sig" field.
func SigIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldSig, vs...))
}

// SigNotIn applies the NotIn predicate on the "sig" field.
func SigNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldSig, vs...))
}

// SigGT applies the GT predicate on the "sig" field.
func SigGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldSig, v))
}

// SigGTE applies the GTE predicate on the "sig" field.
func SigGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldSig, v))
}

// SigLT applies the LT predicate on the "sig" field.
func SigLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldSig, v))
}

// SigLTE applies the LTE predicate on the "sig" field.
func SigLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldSig, v))
}

// SigContains applies the Contains predicate on the "sig" field.
func SigContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldSig, v))
}

// SigHasPrefix applies the HasPrefix predicate on the "sig" field.
func SigHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldSig, v))
}

// SigHasSuffix applies the HasSuffix predicate on the "sig" field.
func SigHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldSig, v))
}

// SigEqualFold applies the EqualFold predicate on the "sig" field.
func SigEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldSig, v))
}

// SigContainsFold applies the ContainsFold predicate on the "sig" field.
func SigContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldSig, v))
}

// PkEQ applies the EQ predicate on the "pk" field.
func PkEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldPk, v))
}

// PkNEQ applies the NEQ predicate on the "pk" field.
func PkNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldPk, v))
}

// PkIn applies the In predicate on the "pk" field.
func PkIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldPk, vs...))
}

// PkNotIn applies the NotIn predicate on the "pk" field.
func PkNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldPk, vs...))
}

// PkGT applies the GT predicate on the "pk" field.
func PkGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldPk, v))
}

// PkGTE applies the GTE predicate on the "pk" field.
func PkGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldPk, v))
}

// PkLT applies the LT predicate on the "pk" field.
func PkLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldPk, v))
}

// PkLTE applies the LTE predicate on the "pk" field.
func PkLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldPk, v))
}

// PkContains applies the Contains predicate on the "pk" field.
func PkContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldPk, v))
}

// PkHasPrefix applies the HasPrefix predicate on the "pk" field.
func PkHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldPk, v))
}

// PkHasSuffix applies the HasSuffix predicate on the "pk" field.
func PkHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldPk, v))
}

// PkEqualFold applies the EqualFold predicate on the "pk" field.
func PkEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldPk, v))
}

// PkContainsFold applies the ContainsFold predicate on the "pk" field.
func PkContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldPk, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Record) predicate.Record {
	return predicate.Record(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Record) predicate.Record {
	return predicate.Record(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Record) predicate.Record {
	return predicate.Record(sql.NotPredicates(p))
}
