// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marukun712/polka/pds/ent/record"
)

// RecordCreate is the builder for creating a Record entity.
type RecordCreate struct {
	config
	mutation *RecordMutation
	hooks    []Hook
}

// SetContent sets the "content" field.
func (_c *RecordCreate) SetContent(v string) *RecordCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetSig sets the "sig" field.
func (_c *RecordCreate) SetSig(v string) *RecordCreate {
	_c.mutation.SetSig(v)
	return _c
}

// SetPk sets the "pk" field.
func (_c *RecordCreate) SetPk(v string) *RecordCreate {
	_c.mutation.SetPk(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RecordCreate) SetID(v string) *RecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RecordMutation object of the builder.
func (_c *RecordCreate) Mutation() *RecordMutation {
	return _c.mutation
}

// Save creates the Record in the database.
func (_c *RecordCreate) Save(ctx context.Context) (*Record, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecordCreate) SaveX(ctx context.Context) *Record {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecordCreate) check() error {
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Record.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := record.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Record.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sig(); !ok {
		return &ValidationError{Name: "sig", err: errors.New(`ent: missing required field "Record.sig"`)}
	}
	if v, ok := _c.mutation.Sig(); ok {
		if err := record.SigValidator(v); err != nil {
			return &ValidationError{Name: "sig", err: fmt.Errorf(`ent: validator failed for field "Record.sig": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pk(); !ok {
		return &ValidationError{Name: "pk", err: errors.New(`ent: missing required field "Record.pk"`)}
	}
	if v, ok := _c.mutation.Pk(); ok {
		if err := record.PkValidator(v); err != nil {
			return &ValidationError{Name: "pk", err: fmt.Errorf(`ent: validator failed for field "Record.pk": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := record.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Record.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RecordCreate) sqlSave(ctx context.Context) (*Record, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Record.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecordCreate) createSpec() (*Record, *sqlgraph.CreateSpec) {
	var (
		_node = &Record{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(record.Table, sqlgraph.NewFieldSpec(record.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(record.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Sig(); ok {
		_spec.SetField(record.FieldSig, field.TypeString, value)
		_node.Sig = value
	}
	if value, ok := _c.mutation.Pk(); ok {
		_spec.SetField(record.FieldPk, field.TypeString, value)
		_node.Pk = value
	}
	return _node, _spec
}

// RecordCreateBulk is the builder for creating many Record entities in bulk.
type RecordCreateBulk struct {
	config
	err      error
	builders []*RecordCreate
}

// Save creates the Record entities in the database.
func (_c *RecordCreateBulk) Save(ctx context.Context) ([]*Record, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Record, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecordCreateBulk) SaveX(ctx context.Context) []*Record {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
