// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/marukun712/polka/pds/ent/record"
	"github.com/marukun712/polka/pds/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescContent is the schema descriptor for content field.
	recordDescContent := recordFields[1].Descriptor()
	// record.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	record.ContentValidator = recordDescContent.Validators[0].(func(string) error)
	// recordDescSig is the schema descriptor for sig field.
	recordDescSig := recordFields[2].Descriptor()
	// record.SigValidator is a validator for the "sig" field. It is called by the builders before save.
	record.SigValidator = recordDescSig.Validators[0].(func(string) error)
	// recordDescPk is the schema descriptor for pk field.
	recordDescPk := recordFields[3].Descriptor()
	// record.PkValidator is a validator for the "pk" field. It is called by the builders before save.
	record.PkValidator = recordDescPk.Validators[0].(func(string) error)
	// recordDescID is the schema descriptor for id field.
	recordDescID := recordFields[0].Descriptor()
	// record.IDValidator is a validator for the "id" field. It is called by the builders before save.
	record.IDValidator = recordDescID.Validators[0].(func(string) error)
}
