package polka:repository@0.1.0;

interface repo {
  use blockstore.{blockstore};

  resource repo {
    new: func(did: string, bs: borrow<blockstore>) -> result<repo, string>;
    open: func(did: string, bs: borrow<blockstore>, cid: string) -> result<repo, string>;
  }
}