// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package blockstore represents the imported interface "polka:repository/blockstore@0.1.0".
package blockstore

import (
	"go.bytecodealliance.org/cm"
)

// Blockstore represents the imported resource "polka:repository/blockstore@0.1.0#blockstore".
//
//	resource blockstore
type Blockstore cm.Resource

// ResourceDrop represents the imported resource-drop for resource "blockstore".
//
// Drops a resource handle.
//
//go:nosplit
func (self Blockstore) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BlockstoreResourceDrop((uint32)(self0))
	return
}

// Get represents the imported method "get".
//
//	get: func(cid: string) -> result<list<u8>, string>
//
//go:nosplit
func (self Blockstore) Get(cid string) (result cm.Result[cm.List[uint8], cm.List[uint8], string]) {
	self0 := cm.Reinterpret[uint32](self)
	cid0, cid1 := cm.LowerString(cid)
	wasmimport_BlockstoreGet((uint32)(self0), (*uint8)(cid0), (uint32)(cid1), &result)
	return
}

// Put represents the imported method "put".
//
//	put: func(data: list<u8>) -> result<string, string>
//
//go:nosplit
func (self Blockstore) Put(data cm.List[uint8]) (result cm.Result[string, string, string]) {
	self0 := cm.Reinterpret[uint32](self)
	data0, data1 := cm.LowerList(data)
	wasmimport_BlockstorePut((uint32)(self0), (*uint8)(data0), (uint32)(data1), &result)
	return
}
