// Code generated by wit-bindgen-go. DO NOT EDIT.

package blockstore

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "polka:repository@0.1.0".

//go:wasmimport polka:repository/blockstore@0.1.0 [resource-drop]blockstore
//go:noescape
func wasmimport_BlockstoreResourceDrop(self0 uint32)

//go:wasmimport polka:repository/blockstore@0.1.0 [method]blockstore.get
//go:noescape
func wasmimport_BlockstoreGet(self0 uint32, cid0 *uint8, cid1 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], string])

//go:wasmimport polka:repository/blockstore@0.1.0 [method]blockstore.put
//go:noescape
func wasmimport_BlockstorePut(self0 uint32, data0 *uint8, data1 uint32, result *cm.Result[string, string, string])
