// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package blockstore represents the imported interface "polka:repository/blockstore@0.1.0".
package blockstore

import (
	"go.bytecodealliance.org/cm"
)

// Blockstore represents the imported resource "polka:repository/blockstore@0.1.0#blockstore".
//
// A content-addressed block storage interface
// This allows external implementations to provide storage backends
//
//	resource blockstore
type Blockstore cm.Resource

// ResourceDrop represents the imported resource-drop for resource "blockstore".
//
// Drops a resource handle.
//
//go:nosplit
func (self Blockstore) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BlockstoreResourceDrop((uint32)(self0))
	return
}

// Delete represents the imported method "delete".
//
// Delete a block from the store
// Returns true if deleted, false if not found, or an error
//
//	delete: func(cid: string) -> result<bool, string>
//
//go:nosplit
func (self Blockstore) Delete(cid string) (result cm.Result[string, bool, string]) {
	self0 := cm.Reinterpret[uint32](self)
	cid0, cid1 := cm.LowerString(cid)
	wasmimport_BlockstoreDelete((uint32)(self0), (*uint8)(cid0), (uint32)(cid1), &result)
	return
}

// Get represents the imported method "get".
//
// Get a block by its CID
// Returns the raw block data or an error if not found
//
//	get: func(cid: string) -> result<list<u8>, string>
//
//go:nosplit
func (self Blockstore) Get(cid string) (result cm.Result[cm.List[uint8], cm.List[uint8], string]) {
	self0 := cm.Reinterpret[uint32](self)
	cid0, cid1 := cm.LowerString(cid)
	wasmimport_BlockstoreGet((uint32)(self0), (*uint8)(cid0), (uint32)(cid1), &result)
	return
}

// Has represents the imported method "has".
//
// Check if a block exists in the store
//
//	has: func(cid: string) -> result<bool, string>
//
//go:nosplit
func (self Blockstore) Has(cid string) (result cm.Result[string, bool, string]) {
	self0 := cm.Reinterpret[uint32](self)
	cid0, cid1 := cm.LowerString(cid)
	wasmimport_BlockstoreHas((uint32)(self0), (*uint8)(cid0), (uint32)(cid1), &result)
	return
}

// Put represents the imported method "put".
//
// Put a block into the store
// Returns the CID of the stored block or an error
//
//	put: func(data: list<u8>) -> result<string, string>
//
//go:nosplit
func (self Blockstore) Put(data cm.List[uint8]) (result cm.Result[string, string, string]) {
	self0 := cm.Reinterpret[uint32](self)
	data0, data1 := cm.LowerList(data)
	wasmimport_BlockstorePut((uint32)(self0), (*uint8)(data0), (uint32)(data1), &result)
	return
}
