// Code generated by wit-bindgen-go. DO NOT EDIT.

package repo

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// CreateResultShape is used for storage in variant or result types.
type CreateResultShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(CreateResult{})]byte
}

// GetResultShape is used for storage in variant or result types.
type GetResultShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(GetResult{})]byte
}

// UnsignedShape is used for storage in variant or result types.
type UnsignedShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Unsigned{})]byte
}

func lift_Unsigned(f0 *uint8, f1 uint32, f2 uint64, f3 *uint8, f4 uint32, f5 *uint8, f6 uint32) (v Unsigned) {
	v.Did = cm.LiftString[string](f0, f1)
	v.Version = (int64)(f2)
	v.Data = cm.LiftString[string](f3, f4)
	v.Rev = cm.LiftString[string](f5, f6)
	return
}
