// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package repo represents the exported interface "polka:repository/repo@0.1.0".
package repo

import (
	"go.bytecodealliance.org/cm"
)

// CommitRequest represents the record "polka:repository/repo@0.1.0#commit-request".
//
//	record commit-request {
//		did: string,
//		version: s64,
//		prev: string,
//		data: string,
//		rev: string,
//	}
type CommitRequest struct {
	_       cm.HostLayout `json:"-"`
	Did     string        `json:"did"`
	Version int64         `json:"version"`
	Prev    string        `json:"prev"`
	Data    string        `json:"data"`
	Rev     string        `json:"rev"`
}

// CreateResult represents the record "polka:repository/repo@0.1.0#create-result".
//
//	record create-result {
//		cid: string,
//		tid: string,
//	}
type CreateResult struct {
	_   cm.HostLayout `json:"-"`
	Cid string        `json:"cid"`
	Tid string        `json:"tid"`
}

// GetResult represents the record "polka:repository/repo@0.1.0#get-result".
//
//	record get-result {
//		cid: string,
//		data: string,
//	}
type GetResult struct {
	_    cm.HostLayout `json:"-"`
	Cid  string        `json:"cid"`
	Data string        `json:"data"`
}
