// Code generated by wit-bindgen-go. DO NOT EDIT.

package repo

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "polka:repository/repo@0.1.0".
var Exports struct {
	// Open represents the caller-defined, exported function "open".
	//
	//	open: func(did: string)
	Open func(did string)

	// CreateRecord represents the caller-defined, exported function "create-record".
	//
	//	create-record: func(nsid: string, data: string) -> result<create-result, string>
	CreateRecord func(nsid string, data string) (result cm.Result[CreateResultShape, CreateResult, string])

	// GetRecord represents the caller-defined, exported function "get-record".
	//
	//	get-record: func(rpath: string) -> result<get-result, string>
	GetRecord func(rpath string) (result cm.Result[GetResultShape, GetResult, string])

	// UpdateRecord represents the caller-defined, exported function "update-record".
	//
	//	update-record: func(rpath: string, data: string) -> result<bool, string>
	UpdateRecord func(rpath string, data string) (result cm.Result[string, bool, string])

	// DeleteRecord represents the caller-defined, exported function "delete-record".
	//
	//	delete-record: func(rpath: string) -> result<bool, string>
	DeleteRecord func(rpath string) (result cm.Result[string, bool, string])

	// GetUnsigned represents the caller-defined, exported function "get-unsigned".
	//
	//	get-unsigned: func() -> result<unsigned, string>
	GetUnsigned func() (result cm.Result[UnsignedShape, Unsigned, string])

	// Commit represents the caller-defined, exported function "commit".
	//
	//	commit: func(commit: unsigned, sig: string) -> result<bool, string>
	Commit func(commit Unsigned, sig string) (result cm.Result[string, bool, string])
}
