// Code generated by wit-bindgen-go. DO NOT EDIT.

package repo

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "polka:repository@0.1.0".

//go:wasmexport polka:repository/repo@0.1.0#new
//export polka:repository/repo@0.1.0#new
func wasmexport_New(did0 *uint8, did1 uint32, bs0 uint32) (result *cm.Result[string, bool, string]) {
	did := cm.LiftString[string]((*uint8)(did0), (uint32)(did1))
	bs := cm.Reinterpret[cm.Rep]((uint32)(bs0))
	result_ := Exports.New(did, bs)
	result = &result_
	return
}

//go:wasmexport polka:repository/repo@0.1.0#open
//export polka:repository/repo@0.1.0#open
func wasmexport_Open(did0 *uint8, did1 uint32, bs0 uint32, cid0 *uint8, cid1 uint32) (result *cm.Result[string, bool, string]) {
	did := cm.LiftString[string]((*uint8)(did0), (uint32)(did1))
	bs := cm.Reinterpret[cm.Rep]((uint32)(bs0))
	cid := cm.LiftString[string]((*uint8)(cid0), (uint32)(cid1))
	result_ := Exports.Open(did, bs, cid)
	result = &result_
	return
}

//go:wasmexport polka:repository/repo@0.1.0#create-record
//export polka:repository/repo@0.1.0#create-record
func wasmexport_CreateRecord(nsid0 *uint8, nsid1 uint32, data0 *uint8, data1 uint32) (result *cm.Result[CreateResultShape, CreateResult, string]) {
	nsid := cm.LiftString[string]((*uint8)(nsid0), (uint32)(nsid1))
	data := cm.LiftString[string]((*uint8)(data0), (uint32)(data1))
	result_ := Exports.CreateRecord(nsid, data)
	result = &result_
	return
}

//go:wasmexport polka:repository/repo@0.1.0#get-record
//export polka:repository/repo@0.1.0#get-record
func wasmexport_GetRecord(rpath0 *uint8, rpath1 uint32) (result *cm.Result[GetResultShape, GetResult, string]) {
	rpath := cm.LiftString[string]((*uint8)(rpath0), (uint32)(rpath1))
	result_ := Exports.GetRecord(rpath)
	result = &result_
	return
}

//go:wasmexport polka:repository/repo@0.1.0#update-record
//export polka:repository/repo@0.1.0#update-record
func wasmexport_UpdateRecord(rpath0 *uint8, rpath1 uint32, data0 *uint8, data1 uint32) (result *cm.Result[string, bool, string]) {
	rpath := cm.LiftString[string]((*uint8)(rpath0), (uint32)(rpath1))
	data := cm.LiftString[string]((*uint8)(data0), (uint32)(data1))
	result_ := Exports.UpdateRecord(rpath, data)
	result = &result_
	return
}

//go:wasmexport polka:repository/repo@0.1.0#delete-record
//export polka:repository/repo@0.1.0#delete-record
func wasmexport_DeleteRecord(rpath0 *uint8, rpath1 uint32) (result *cm.Result[string, bool, string]) {
	rpath := cm.LiftString[string]((*uint8)(rpath0), (uint32)(rpath1))
	result_ := Exports.DeleteRecord(rpath)
	result = &result_
	return
}

//go:wasmexport polka:repository/repo@0.1.0#get-unsigned
//export polka:repository/repo@0.1.0#get-unsigned
func wasmexport_GetUnsigned() (result *cm.Result[UnsignedShape, Unsigned, string]) {
	result_ := Exports.GetUnsigned()
	result = &result_
	return
}

//go:wasmexport polka:repository/repo@0.1.0#commit
//export polka:repository/repo@0.1.0#commit
func wasmexport_Commit(commit0 *uint8, commit1 uint32, commit2 uint64, commit3 *uint8, commit4 uint32, commit5 *uint8, commit6 uint32, sig0 *uint8, sig1 uint32) (result *cm.Result[string, bool, string]) {
	commit := lift_Unsigned((*uint8)(commit0), (uint32)(commit1), (uint64)(commit2), (*uint8)(commit3), (uint32)(commit4), (*uint8)(commit5), (uint32)(commit6))
	sig := cm.LiftString[string]((*uint8)(sig0), (uint32)(sig1))
	result_ := Exports.Commit(commit, sig)
	result = &result_
	return
}
