// Generated by `wit-bindgen` 0.47.0. DO NOT EDIT!
// Options used:
//   * default-bindings-module: "crate::repository"
#[allow(dead_code, clippy::all)]
pub mod polka {
  pub mod repository {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod blockstore {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn read_block(cid: &[u8],) -> _rt::Vec::<u8>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let vec0 = cid;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "polka:repository/blockstore@0.1.0")]
          unsafe extern "C" {
            #[link_name = "read-block"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = *ptr1.add(0).cast::<*mut u8>();
          let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len5 = l4;
          let result6 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
          result6
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn write_block(codec: u64,hash: u64,contents: &[u8],) -> _rt::Vec::<u8>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let vec0 = contents;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "polka:repository/blockstore@0.1.0")]
          unsafe extern "C" {
            #[link_name = "write-block"]
            fn wit_import2(_: i64, _: i64, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: i64, _: i64, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(_rt::as_i64(&codec), _rt::as_i64(&hash), ptr0.cast_mut(), len0, ptr1);
          let l3 = *ptr1.add(0).cast::<*mut u8>();
          let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len5 = l4;
          let result6 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
          result6
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod crypto {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn sign(bytes: &[u8],) -> _rt::Vec::<u8>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let vec0 = bytes;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "polka:repository/crypto@0.1.0")]
          unsafe extern "C" {
            #[link_name = "sign"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = *ptr1.add(0).cast::<*mut u8>();
          let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len5 = l4;
          let result6 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
          result6
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod polka {
    pub mod repository {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod repo {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        #[derive(Clone)]
        pub struct GetResult {
          pub rpath: _rt::String,
          pub data: _rt::String,
        }
        impl ::core::fmt::Debug for GetResult {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("GetResult").field("rpath", &self.rpath).field("data", &self.data).finish()
          }
        }

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct Repo{
          handle: _rt::Resource<Repo>,
        }

        type _RepoRep<T> = Option<T>;

        impl Repo{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `Repo`.
          pub fn new<T: GuestRepo>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _RepoRep<T> = Some(val);
            let ptr: *mut _RepoRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestRepo>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestRepo>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestRepo>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestRepo` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _RepoRep<T>) };
          }

          fn as_ptr<T: GuestRepo>(&self) -> *mut _RepoRep<T> {
            Repo::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`Repo`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct RepoBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a Repo>,
        }

        impl<'a> RepoBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestRepo>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _RepoRep<T> {
            Repo::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for Repo{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]polka:repository/repo@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]repo"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_method_repo_get_cid_cabi<T: GuestRepo>(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result1 = {
          let len0 = arg2;
          let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
          T::get_cid(RepoBorrow::lift(arg0 as u32 as usize).get(), _rt::string_lift(bytes0))
        };
        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
        match result1 {
          Ok(e) => { {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            let vec3 = (e.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
          } },
          Err(e) => { {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec4 = (e.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
          } },
        };ptr2
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_method_repo_get_cid<T: GuestRepo>(arg0: *mut u8,) { unsafe {
        let l0 = i32::from(*arg0.add(0).cast::<u8>());
        match l0 {
          0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
          },
          _ => {
            let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
          },
        }
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_method_repo_get_record_cabi<T: GuestRepo>(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result1 = {
        let len0 = arg2;
        let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
        T::get_record(RepoBorrow::lift(arg0 as u32 as usize).get(), _rt::string_lift(bytes0))
      };
      let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result1 {
        Ok(e) => { {
          *ptr2.add(0).cast::<u8>() = (0i32) as u8;
          let GetResult{ rpath:rpath3, data:data3, } = e;
          let vec4 = (rpath3.into_bytes()).into_boxed_slice();
          let ptr4 = vec4.as_ptr().cast::<u8>();
          let len4 = vec4.len();
          ::core::mem::forget(vec4);
          *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
          *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
          let vec5 = (data3.into_bytes()).into_boxed_slice();
          let ptr5 = vec5.as_ptr().cast::<u8>();
          let len5 = vec5.len();
          ::core::mem::forget(vec5);
          *ptr2.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
          *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
        } },
        Err(e) => { {
          *ptr2.add(0).cast::<u8>() = (1i32) as u8;
          let vec6 = (e.into_bytes()).into_boxed_slice();
          let ptr6 = vec6.as_ptr().cast::<u8>();
          let len6 = vec6.len();
          ::core::mem::forget(vec6);
          *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
          *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6.cast_mut();
        } },
      };ptr2
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_method_repo_get_record<T: GuestRepo>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => {
          let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l1, l2, 1);
          let l3 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l4 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l3, l4, 1);
        },
        _ => {
          let l5 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l6 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l5, l6, 1);
        },
      }
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_method_repo_get_records_cabi<T: GuestRepo>(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result1 = {
      let len0 = arg2;
      let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
      T::get_records(RepoBorrow::lift(arg0 as u32 as usize).get(), _rt::string_lift(bytes0))
    };
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
      Ok(e) => { {
        *ptr2.add(0).cast::<u8>() = (0i32) as u8;
        let vec6 = e;
        let len6 = vec6.len();
        let layout6 = _rt::alloc::Layout::from_size_align(vec6.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result6, _cleanup6) = wit_bindgen::rt::Cleanup::new(layout6);if let Some(cleanup) = _cleanup6 { cleanup.forget(); }
        for (i, e) in vec6.into_iter().enumerate() {
          let base = result6.add(i * (4*::core::mem::size_of::<*const u8>()));
          {
            let GetResult{ rpath:rpath3, data:data3, } = e;
            let vec4 = (rpath3.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
            let vec5 = (data3.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
          }
        }
        *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result6;
      } },
      Err(e) => { {
        *ptr2.add(0).cast::<u8>() = (1i32) as u8;
        let vec7 = (e.into_bytes()).into_boxed_slice();
        let ptr7 = vec7.as_ptr().cast::<u8>();
        let len7 = vec7.len();
        ::core::mem::forget(vec7);
        *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr7.cast_mut();
      } },
    };ptr2
  } }
  #[doc(hidden)]
  #[allow(non_snake_case)]
  pub unsafe fn __post_return_method_repo_get_records<T: GuestRepo>(arg0: *mut u8,) { unsafe {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
      0 => {
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base7 = l1;
        let len7 = l2;
        for i in 0..len7 {
          let base = base7.add(i * (4*::core::mem::size_of::<*const u8>()));
          {
            let l3 = *base.add(0).cast::<*mut u8>();
            let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
            let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l5, l6, 1);
          }
        }
        _rt::cabi_dealloc(base7, len7 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      },
      _ => {
        let l8 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l9 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l8, l9, 1);
      },
    }
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_method_repo_all_records_cabi<T: GuestRepo>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();let result0 = {
    T::all_records(RepoBorrow::lift(arg0 as u32 as usize).get())
  };
  let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
  match result0 {
    Ok(e) => { {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
      let vec5 = e;
      let len5 = vec5.len();
      let layout5 = _rt::alloc::Layout::from_size_align(vec5.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
      let (result5, _cleanup5) = wit_bindgen::rt::Cleanup::new(layout5);if let Some(cleanup) = _cleanup5 { cleanup.forget(); }
      for (i, e) in vec5.into_iter().enumerate() {
        let base = result5.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let GetResult{ rpath:rpath2, data:data2, } = e;
          let vec3 = (rpath2.into_bytes()).into_boxed_slice();
          let ptr3 = vec3.as_ptr().cast::<u8>();
          let len3 = vec3.len();
          ::core::mem::forget(vec3);
          *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
          *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
          let vec4 = (data2.into_bytes()).into_boxed_slice();
          let ptr4 = vec4.as_ptr().cast::<u8>();
          let len4 = vec4.len();
          ::core::mem::forget(vec4);
          *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
          *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
        }
      }
      *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
      *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result5;
    } },
    Err(e) => { {
      *ptr1.add(0).cast::<u8>() = (1i32) as u8;
      let vec6 = (e.into_bytes()).into_boxed_slice();
      let ptr6 = vec6.as_ptr().cast::<u8>();
      let len6 = vec6.len();
      ::core::mem::forget(vec6);
      *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
      *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6.cast_mut();
    } },
  };ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_repo_all_records<T: GuestRepo>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base7 = l1;
      let len7 = l2;
      for i in 0..len7 {
        let base = base7.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let l3 = *base.add(0).cast::<*mut u8>();
          let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l3, l4, 1);
          let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l5, l6, 1);
        }
      }
      _rt::cabi_dealloc(base7, len7 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    },
    _ => {
      let l8 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l9 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l8, l9, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_repo_get_root_cabi<T: GuestRepo>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::get_root(RepoBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Ok(e) => { {
    *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    let vec2 = (e.into_bytes()).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
  } },
  Err(e) => { {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    let vec3 = (e.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
  } },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_repo_get_root<T: GuestRepo>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
    _ => {
      let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l3, l4, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_repo_create_cabi<T: GuestRepo>(arg0: *mut u8,arg1: *mut u8,arg2: usize,arg3: *mut u8,arg4: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result2 = {
  let len0 = arg2;
  let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
  let len1 = arg4;
  let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
  T::create(RepoBorrow::lift(arg0 as u32 as usize).get(), _rt::string_lift(bytes0), _rt::string_lift(bytes1))
};
let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
match result2 {
  Ok(e) => { {
    *ptr3.add(0).cast::<u8>() = (0i32) as u8;
    let vec4 = (e.into_bytes()).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
  } },
  Err(e) => { {
    *ptr3.add(0).cast::<u8>() = (1i32) as u8;
    let vec5 = (e.into_bytes()).into_boxed_slice();
    let ptr5 = vec5.as_ptr().cast::<u8>();
    let len5 = vec5.len();
    ::core::mem::forget(vec5);
    *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
  } },
};ptr3
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_repo_create<T: GuestRepo>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
    _ => {
      let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l3, l4, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_repo_update_cabi<T: GuestRepo>(arg0: *mut u8,arg1: *mut u8,arg2: usize,arg3: *mut u8,arg4: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result2 = {
  let len0 = arg2;
  let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
  let len1 = arg4;
  let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
  T::update(RepoBorrow::lift(arg0 as u32 as usize).get(), _rt::string_lift(bytes0), _rt::string_lift(bytes1))
};
let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
match result2 {
  Ok(e) => { {
    *ptr3.add(0).cast::<u8>() = (0i32) as u8;
    let vec4 = (e.into_bytes()).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
  } },
  Err(e) => { {
    *ptr3.add(0).cast::<u8>() = (1i32) as u8;
    let vec5 = (e.into_bytes()).into_boxed_slice();
    let ptr5 = vec5.as_ptr().cast::<u8>();
    let len5 = vec5.len();
    ::core::mem::forget(vec5);
    *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
  } },
};ptr3
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_repo_update<T: GuestRepo>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
    _ => {
      let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l3, l4, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_repo_delete_cabi<T: GuestRepo>(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result1 = {
  let len0 = arg2;
  let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
  T::delete(RepoBorrow::lift(arg0 as u32 as usize).get(), _rt::string_lift(bytes0))
};
let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
match result1 {
  Ok(e) => { {
    *ptr2.add(0).cast::<u8>() = (0i32) as u8;
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (match e { true => 1, false => 0 }) as u8;
  } },
  Err(e) => { {
    *ptr2.add(0).cast::<u8>() = (1i32) as u8;
    let vec3 = (e.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
  } },
};ptr2
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_repo_delete<T: GuestRepo>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_create_cabi<T: Guest>(arg0: *mut u8,arg1: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result1 = {
  let len0 = arg1;
  let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
  T::create(_rt::string_lift(bytes0))
};
let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
match result1 {
  Ok(e) => { {
    *ptr2.add(0).cast::<u8>() = (0i32) as u8;
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<i32>() = (e).take_handle() as i32;
  } },
  Err(e) => { {
    *ptr2.add(0).cast::<u8>() = (1i32) as u8;
    let vec3 = (e.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
  } },
};ptr2
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_create<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_open_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result2 = {
  let len0 = arg1;
  let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
  let len1 = arg3;
  let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
  T::open(_rt::string_lift(bytes0), _rt::string_lift(bytes1))
};
let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
match result2 {
  Ok(e) => { {
    *ptr3.add(0).cast::<u8>() = (0i32) as u8;
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<i32>() = (e).take_handle() as i32;
  } },
  Err(e) => { {
    *ptr3.add(0).cast::<u8>() = (1i32) as u8;
    let vec4 = (e.into_bytes()).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
  } },
};ptr3
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_open<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
  }
} }
pub trait Guest {
  type Repo: GuestRepo;
  #[allow(async_fn_in_trait)]
  fn create(did: _rt::String,) -> Result<Repo,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn open(did: _rt::String,cid: _rt::String,) -> Result<Repo,_rt::String>;
}
pub trait GuestRepo: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]polka:repository/repo@0.1.0")]
    unsafe extern "C" {
      #[link_name = "[resource-new]repo"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]polka:repository/repo@0.1.0")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]repo"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  #[allow(async_fn_in_trait)]
  fn get_cid(&self,rpath: _rt::String,) -> Result<_rt::String,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn get_record(&self,rpath: _rt::String,) -> Result<GetResult,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn get_records(&self,nsid: _rt::String,) -> Result<_rt::Vec::<GetResult>,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn all_records(&self,) -> Result<_rt::Vec::<GetResult>,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn get_root(&self,) -> Result<_rt::String,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn create(&self,rpath: _rt::String,data: _rt::String,) -> Result<_rt::String,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn update(&self,rpath: _rt::String,data: _rt::String,) -> Result<_rt::String,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn delete(&self,rpath: _rt::String,) -> Result<bool,_rt::String>;
}
#[doc(hidden)]

macro_rules! __export_polka_repository_repo_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "polka:repository/repo@0.1.0#[method]repo.get-cid")]
    unsafe extern "C" fn export_method_repo_get_cid(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_repo_get_cid_cabi::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#[method]repo.get-cid")]
    unsafe extern "C" fn _post_return_method_repo_get_cid(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_repo_get_cid::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#[method]repo.get-record")]
    unsafe extern "C" fn export_method_repo_get_record(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_repo_get_record_cabi::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#[method]repo.get-record")]
    unsafe extern "C" fn _post_return_method_repo_get_record(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_repo_get_record::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#[method]repo.get-records")]
    unsafe extern "C" fn export_method_repo_get_records(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_repo_get_records_cabi::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#[method]repo.get-records")]
    unsafe extern "C" fn _post_return_method_repo_get_records(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_repo_get_records::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#[method]repo.all-records")]
    unsafe extern "C" fn export_method_repo_all_records(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_repo_all_records_cabi::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#[method]repo.all-records")]
    unsafe extern "C" fn _post_return_method_repo_all_records(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_repo_all_records::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#[method]repo.get-root")]
    unsafe extern "C" fn export_method_repo_get_root(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_repo_get_root_cabi::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#[method]repo.get-root")]
    unsafe extern "C" fn _post_return_method_repo_get_root(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_repo_get_root::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#[method]repo.create")]
    unsafe extern "C" fn export_method_repo_create(arg0: *mut u8,arg1: *mut u8,arg2: usize,arg3: *mut u8,arg4: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_repo_create_cabi::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0, arg1, arg2, arg3, arg4) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#[method]repo.create")]
    unsafe extern "C" fn _post_return_method_repo_create(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_repo_create::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#[method]repo.update")]
    unsafe extern "C" fn export_method_repo_update(arg0: *mut u8,arg1: *mut u8,arg2: usize,arg3: *mut u8,arg4: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_repo_update_cabi::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0, arg1, arg2, arg3, arg4) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#[method]repo.update")]
    unsafe extern "C" fn _post_return_method_repo_update(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_repo_update::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#[method]repo.delete")]
    unsafe extern "C" fn export_method_repo_delete(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_repo_delete_cabi::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#[method]repo.delete")]
    unsafe extern "C" fn _post_return_method_repo_delete(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_repo_delete::<<$ty as $($path_to_types)*::Guest>::Repo>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#create")]
    unsafe extern "C" fn export_create(arg0: *mut u8,arg1: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_create_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#create")]
    unsafe extern "C" fn _post_return_create(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_create::<$ty>(arg0) }
    }
    #[unsafe(export_name = "polka:repository/repo@0.1.0#open")]
    unsafe extern "C" fn export_open(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_open_cabi::<$ty>(arg0, arg1, arg2, arg3) }
    }
    #[unsafe(export_name = "cabi_post_polka:repository/repo@0.1.0#open")]
    unsafe extern "C" fn _post_return_open(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_open::<$ty>(arg0) }
    }

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "polka:repository/repo@0.1.0#[dtor]repo")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::Repo::dtor::<
          <$ty as $($path_to_types)*::Guest>::Repo
          >(rep)
        }
      }
    };
    
  };);
}
#[doc(hidden)]
pub(crate) use __export_polka_repository_repo_0_1_0_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 5*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 5*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::vec::Vec;

  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  pub use alloc_crate::string::String;


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::boxed::Box;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::alloc;
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_repository_impl {
  ($ty:ident) => (crate::repository::export!($ty with_types_in crate::repository););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::polka::repository::repo::__export_polka_repository_repo_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::polka::repository::repo);
  )
}
#[doc(inline)]
pub(crate) use __export_repository_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.47.0:polka:repository@0.1.0:repository:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 833] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc0\x05\x01A\x02\x01\
A\x06\x01B\x05\x01p}\x01@\x01\x03cid\0\0\0\x04\0\x0aread-block\x01\x01\x01@\x03\x05\
codecw\x04hashw\x08contents\0\0\0\x04\0\x0bwrite-block\x01\x02\x03\0!polka:repos\
itory/blockstore@0.1.0\x05\0\x01B\x03\x01p}\x01@\x01\x05bytes\0\0\0\x04\0\x04sig\
n\x01\x01\x03\0\x1dpolka:repository/crypto@0.1.0\x05\x01\x01B\x1e\x01r\x02\x05rp\
aths\x04datas\x04\0\x0aget-result\x03\0\0\x04\0\x04repo\x03\x01\x01h\x02\x01j\x01\
s\x01s\x01@\x02\x04self\x03\x05rpaths\0\x04\x04\0\x14[method]repo.get-cid\x01\x05\
\x01j\x01\x01\x01s\x01@\x02\x04self\x03\x05rpaths\0\x06\x04\0\x17[method]repo.ge\
t-record\x01\x07\x01p\x01\x01j\x01\x08\x01s\x01@\x02\x04self\x03\x04nsids\0\x09\x04\
\0\x18[method]repo.get-records\x01\x0a\x01@\x01\x04self\x03\0\x09\x04\0\x18[meth\
od]repo.all-records\x01\x0b\x01@\x01\x04self\x03\0\x04\x04\0\x15[method]repo.get\
-root\x01\x0c\x01@\x03\x04self\x03\x05rpaths\x04datas\0\x04\x04\0\x13[method]rep\
o.create\x01\x0d\x04\0\x13[method]repo.update\x01\x0d\x01j\x01\x7f\x01s\x01@\x02\
\x04self\x03\x05rpaths\0\x0e\x04\0\x13[method]repo.delete\x01\x0f\x01i\x02\x01j\x01\
\x10\x01s\x01@\x01\x03dids\0\x11\x04\0\x06create\x01\x12\x01@\x02\x03dids\x03cid\
s\0\x11\x04\0\x04open\x01\x13\x04\0\x1bpolka:repository/repo@0.1.0\x05\x02\x04\0\
!polka:repository/repository@0.1.0\x04\0\x0b\x10\x01\0\x0arepository\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.240.0\x10wit-bindgen-rus\
t\x060.47.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

